FROM zzswang/docker-nginx-react:latest

ENV APP_DIR=/app
#  \
#     API_PLACEHOLDER=/api/v1 \
#     API_GATEWAY=https://api.your.damain

## Suppose your app is in the dist directory.
COPY ./build /app